// This file was mostly generated by AI

#include <pthread.h>
#include <stdbool.h>
#include <stdio.h>
#include <windows.h>

#include "jap_notify.h"

#define WM_TRAYICON (WM_USER + 1)

NOTIFYICONDATA nid;
pthread_t t_tray;

LRESULT CALLBACK WindowProc(HWND hwnd, UINT uMsg, WPARAM wParam,
                            LPARAM lParam) {
    return DefWindowProc(hwnd, uMsg, wParam, lParam);
}

void *tray_notification(void *arg) {
    // Step 1: Register a window class
    WNDCLASS wc = {0};
    wc.lpfnWndProc = WindowProc;
    wc.hInstance = GetModuleHandle(NULL);
    wc.lpszClassName = "TrayClass";

    if (!RegisterClass(&wc)) {
        return NULL;
    }

    // Step 2: Create a hidden window
    HWND hwnd = CreateWindowEx(0, wc.lpszClassName, "TrayWindow", 0, 0, 0, 0, 0,
                               NULL, NULL, wc.hInstance, NULL);

    if (!hwnd) {
        return NULL;
    }

    // Step 3: Add an icon to the system tray
    nid.cbSize = sizeof(NOTIFYICONDATA);
    nid.hWnd = hwnd;
    nid.uID = 1;
    nid.uFlags = NIF_ICON | NIF_MESSAGE | NIF_TIP | NIF_INFO;
    nid.uCallbackMessage = WM_TRAYICON;
    nid.hIcon = (HICON)LoadImage(NULL, "res/icon.ico", IMAGE_ICON, 16, 16,
                                 LR_LOADFROMFILE | LR_DEFAULTSIZE);
    lstrcpy(nid.szTip, "Just Another Pomodoro");

    Shell_NotifyIcon(NIM_ADD, &nid);

    // Step 4: Message loop
    MSG msg;
    while (GetMessage(&msg, NULL, 0, 0)) {
        TranslateMessage(&msg);
        DispatchMessage(&msg);
    }

    // Step 5: Clean up
    Shell_NotifyIcon(NIM_DELETE, &nid);
    DestroyWindow(hwnd);

    return NULL;
}

void jap_clean() {
    PostQuitMessage(0);
    pthread_detach(t_tray);
}

bool jap_notify_init() {
    pthread_create(&t_tray, NULL, tray_notification, NULL);
    atexit(&jap_clean);
    return true;
}

bool jap_notify_show(char *title, char *msg) {
    printf(BELL);

    lstrcpy(nid.szInfoTitle, title);
    lstrcpy(nid.szInfo, msg);
    nid.dwInfoFlags = NIIF_INFO;
    Shell_NotifyIcon(NIM_MODIFY, &nid);

    return true;
}
